### ISSUE TITLE
Add a dropdown filter so that users can filter by genre

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#140]
In the top of EmojiScreen in the filters section, add a dropdown filter so that users can filter by genre. The options for the filter should include all genres in the data.js file and also in the README.md genre chart. The filter should be able to automatically pull any new genres someone adds to an emoji card in the future.

Match the styling to the current filters and use the existing colors on the website. You may need to reconfigure the HTML for the filters section to add in this new dropdown.

One solution for reorganizing is to add an 'advanced filters' section that is collapsable so that you can add the dropdown in an advanced filters section under the current filters and hide it unless clicked on. Eventually we will also want to add a filter for years as well so this would be a good solution to ensure it would be easy to expand and add more filters without cluttering the homepage.

**Comment by cjtangney** [comment]
I'll take a look at this one, too, while I'm working on the year filter! 😅

**Comment by brittanyrw** [comment]
@cjtangney Awesome, I will assign this to you.

**Comment by cjtangney** [comment]
Wanted to drop by here (since it's technically a separate issue 😅) to share my thoughts on this. 

Since each movie / series can potentially belong to a number of different genres, storing them in a `data-attribute` is probably not the right call. To that extent, for this filter at the least, it seems to make sense to just poll the data again and re-draw the DOM with the necessary cards. If that makes sense to you, that's what I'll run with!

At some point, this load may want to be asynchronous, with an application load state, but that's all kind of outside the scope of this issue
