### ISSUE TITLE
Add link for items starting with G in the data.js file 

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#253]
Add the `itemLink` url for shows/movies that start with G in the data.js file.

You can refer to [the link section](https://github.com/brittanyrw/emojiscreen#card-overview) in the README.

For TV shows and movies, add the [IMDB page](https://www.imdb.com/) link.

For musicals link the [Playbill archive page](http://www.playbill.com/vault) for the show. Make sure the Playbill link is for the original production. It will say 'original' under the show name on Playbill. Here is an example of [the page you should be linking](http://www.playbill.com/production/les-miserables-broadway-theatre-vault-0000012257) for musicals.

**Comment by gemanepa** [comment]
Hi @brittanyrw , I'll work in this enhancement :) One little thing: 

`    {
        title: "Grease",
        emojiImgs: "🌅👸💞👨‍🎤🚘",
        genres: ["musical", "romance"],
        type: "musical",
        year: 1978
    },`

type here shouldn't be 'movie' instead of 'musical'? I mean, Grease (1978) is a movie of the musical genre, but it's still a movie, right? https://www.imdb.com/title/tt0077631/
So what do you want me to do...
1. Change type to 'movie' and put IMDB link
2. Leave type as it is and put IMDB link
3. Leave type as it is and put Playbill link (which seems like it does not exist)
?

**Comment by brittanyrw** [comment]
@gemanepa nice catch! 👍Yes, please go ahead and update it to movie.
