### ISSUE TITLE
Add a link to EmojiPages to footer

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#294]
Add a link to EmojiPages (https://emojipages.com) to the footer.

This may require redesigning how the footer looks. Feel free to list suggestions below.

**Comment by timrodz** [comment]
@brittanyrw May I take this? :)

If so, I'll come up with an idea for a small, cute re-design of the footer.

**Comment by timrodz** [comment]
Hello 😊 I had a look at the code, and I'd like to propose some small changes:

1. Decrease the margin between paragraphs, so the spacing doesn't feel left out.
1. Add a `<p>` similar to the EmojiBops one, but for EmojiPages.
1. Add project related emojis to the end of lines, e.g. 🎶, 📚

Alternatively, the other sites could be displayed side-to-side, like so: `EmojiBops 🎶 | EmojiPages 📚`. 

Let me know what you think about these.

I also wanted to clarify something for consistency: Should the `<a href>` links take me to the project github repositories, or their published sites?

Github repo links:
- [https://github.com/brittanyrw/emojibops](https://github.com/brittanyrw/emojibops)
- [https://github.com/brittanyrw/emojipages](https://github.com/brittanyrw/emojipages)

Individual Websites:
- [https://emojipages.com](https://emojipages.com)
- [https://emojibops.com](https://emojibops.com/)

I'm asking because there's this code inside the footer:

```html
<p class="companion-project-link">
    Music fan? Check out <a href="https://github.com/brittanyrw/emojibops" target="_blank">EmojiBops</a>
</p>
```

It takes me to [https://github.com/brittanyrw/emojibops](https://github.com/brittanyrw/emojibops), instead of [https://emojibops.com](https://emojibops.com/).

Hope my question is clear. If not, I'm more than happy to run you through it 😊

**Comment by brittanyrw** [comment]
@timrodz Ah yes, for that link. Someone already did a pull request updating the URL so that it points to the live site instead of GitHub for EmojiBops. I just haven't merged it in yet. 

So it should go to the live site instead of the GitHub page.

And your changes sound great!

**Comment by timrodz** [comment]
Awesome, thanks for the clarification!

I played with them aroud for a bit earlier, and wanted to show you the possible outcomes so far:

- Top: side-to-side
- Middle: one below the other
- Bottom: current state

![Possible outcomes](https://i.imgur.com/eQOCbZ7.png)

What do you reckon?

**Comment by brittanyrw** [comment]
I think the middle choice looks the best! 💖
