### ISSUE TITLE
Clean up genres in data.js file

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#691]
In the `data.js` file, let's make the genres uniform so that it will be easier to build filters. 

**Cleaning up genres**

In the `data.js` file, update the genres so that they are all uniform. Make sure that everything with a `type` of `musical` has `musical` listed as a genre as well.

All genres should be `lowercase` and if the genre is more than one word, there should be a `hyphen` instead of space. See below for example. 

Incorrect genre formatting:
```
genres: ["Art House", "International", "Classics", "Drama"]
```

Correct genre formatting:
```
genres: ["art-house", "international", "classics", "drama"]
```

**Comment by faahim** [comment]
Hi @brittanyrw :wave: 

This looks interesting! Can I take this one? :slightly_smiling_face:

**Comment by brittanyrw** [comment]
Hi @faahim, I have assigned this to you. Thanks for working on this!

**Comment by faahim** [comment]
Awesome! Thanks a ton!
I'll be back with PR ASAP :smile: 

Just to be clear I understood this correctly, the main criteria here is that the items in genres array need to be
+ all lowercased
+ use a hyphen instead of space, and
+ if the type is `musical`, the genres array must contain the item `musical`

Hopefully, I'm not missing anything?

**Comment by brittanyrw** [comment]
Yep, that is all correct!

**Comment by faahim** [comment]
Great! Thanks so much! :smile:

**Comment by faahim** [comment]
@brittanyrw Just submitted the PR! Thanks a lot for allowing me to do this. It was a fun hacking session! :smile:
